### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by zamazan4ik** [MolecularMatters/psd_sdk#1]
Hi!
Do you plan to add Linux support for your library? Because I cann ot understand is it possible to build and use the library on Linux-based OS :(

Thank you!

**Comment by MolecularMatters** [comment]
At the moment, the library only builds for Windows.
I added a few comments to the README regarding supported platforms and porting.

We'll gladly accept pull requests!

**Comment by melMass** [comment]
I started to add `if guards for Mac` where needed and replacing 'Windows.h' functions with 'stdio.h' ones yesterday. Almost there but I need to learn how Windows.h deals with I/O which I have no clue about, to properly convert `PsdNativeFile` which is the last one needed for a working mac version

**Comment by MolecularMatters** [comment]
> 
> 
> I started to add `if guards for Mac` where needed and replacing 'Windows.h' functions with 'stdio.h' ones yesterday. Almost there but I need to learn how Windows.h deals with I/O which I have no clue about, to properly convert `PsdNativeFile` which is the last one needed for a working mac version

I don't think you have to know how Windows async I/O works in order to implement it for Mac.
The most important functions in the "File" interface are "DoRead", "DoWrite" and the corresponding "DoWait*" operations.

The read and write functions need to start an async request to load "count" bytes into the given "buffer" at file position "position". They also need to return any kind of object (dubbed "File::ReadOperation" and "File::WriteOperation") that uniquely identifies the I/O request made by the user. On Windows, those are "OVERLAPPED" objects. On Mac it will be something different.

The wait operations simply wait until the given operation is finished.

**Comment by oluseyi** [comment]
Saw this issue while browsing, and that the conversation had veered into a discussion of Mac support. I've got a crude initial port compiling, but there are some issues still to debug: https://github.com/MolecularMatters/psd_sdk/pull/3

> The read and write functions need to start an async request to load "count" bytes into the given "buffer" at file position "position". They also need to return any kind of object (dubbed "File::ReadOperation" and "File::WriteOperation") that uniquely identifies the I/O request made by the user. On Windows, those are "OVERLAPPED" objects. On Mac it will be something different.

Indeed. On the Mac we use a [`readabilityHandler`](https://developer.apple.com/documentation/foundation/nsfilehandle/1412413-readabilityhandler?language=objc)/[`writeabilityHandler`](https://developer.apple.com/documentation/foundation/nsfilehandle/1415367-writeabilityhandler?language=objc) on an `NSFileHandle`, which is natively asynchronous and renders the `DoWaitFor[Read|Write]` methods almost moot. This will necessitate a little thought about the interface, but I'd appreciate some guidance on typical usage.

**Comment by MolecularMatters** [comment]
Linux is available now thanks to PR 4768e6068b3944d5031400d49e23f44ec5c29bba.
