### ISSUE TITLE
[PsdSamples] Config files for sample PSD paths

### ISSUE THREAD

**Issue by oluseyi** [MolecularMatters/psd_sdk#4]
I've been working on [porting psd_sdk to macOS](https://github.com/MolecularMatters/psd_sdk/pull/3), and I've run into some paper cuts driven by the software having been Windows-only and thus baked in some platform assumptions:

1. POSIX systems use a different path separator than the Windows default, though I believe Windows APIs will do the right thing if you supply them with forward slash-separated paths? So perhaps we should standardize on that?

1. Xcode is pretty weird about the working directory of your executable in debug, building it somewhere deep inside of the developer directory hierarchy. Using _relative paths_ to locate files is thus a bit of a problem. Perhaps a configuration file of some sort would help here?

I don't have access to a Windows box right now, but I can put up a PR for this and hopefully @MolecularMatters can test and verify that it works as intended on Windows. It's a slight pain because we don't have an installer, so we can't automatically configure the paths for a great "out-of-the-box" experience, but I think that's not too much of a burden for an SDK sample.

---

Alternately, of course, we could have the sample spawn an open dialog… 😛

**Comment by MolecularMatters** [comment]
Regarding 1.: Windows should handle forward slashes fine. I can do the change for the sample code; I don't think the rest of the code should have any notion of path separators.

Regarding 2.: I wouldn't want the sample to be bloated with loading and parsing config files. It should be really simple code to show users how to use the API and not be concerned with OS-specific issues or setup.

That being said, I wouldn't mind if we were to add code to the sample that returns the sample path, which can be different on each platform, e.g.

std::string GetSamplePath(void)
{
#ifdef _WIN32
#elif __APPLE__
#endif
}

We can also have separate paths for the read and write sample.
Does macOS have something similar to Windows' %LocalAppData%?
I would suspect so. Maybe that's a good destination for writing the sample because you shouldn't run into any permission issues there.
Choose whatever path you see fit, I'm not too familiar with these things on macOS.

**Comment by MolecularMatters** [comment]
I modified the sample code to more easily use different paths for input and output data in this commit: https://github.com/MolecularMatters/psd_sdk/commit/4bbd7436408a7926a3c28a41642fdaf116415e49

Can you work with that or do you think there will still be problems with this solution?

**Comment by oluseyi** [comment]
This was plenty good, thanks. Perhaps even unnecessary; simply switching to forward slash as the uniform delimiter would have done the trick.

In terms of the specific path, I agree, no need to bloat the sample with all that. I ended up adding a custom working directory to my build scheme when I wanted to debug in Xcode. `PsdSamples` runs with only one runtime error message about a file section signature mismatch. It generates 7 targa files (2 of them layer masks) and 3 PSDs. I think this issue can be considered closed.
